baseurl = "/"
languageCode = "en-us"
title = "Lei Yan's Cool Website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true
hasCJKLanguage = true
[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; Lei Yan 2018 -- 2019 | [Github](https://github.com/louieyan) | [Zhihu](https://www.zhihu.com/people/yan-lei-8-9/) | [QQ](http://wpa.qq.com/msgrd?v=3&uin=1216360090&site=qq&menu=yes)"
